[package]
name = "thetuss"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }

[dependencies.serenity]
version = "0.11.6"
default-features = true
